/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void maxBuyPriceSliderEvent(GCustomSlider source, GEvent event) { //_CODE_:maxBuyingPriceSlider:211829:
  maxBuyingPrice = floor(maxBuyingPriceSlider.getValueF()*100);
} //_CODE_:maxBuyingPriceSlider:211829:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  maxBuyingPriceSlider = new GCustomSlider(this, 47, 154, 348, 80, "grey_blue");
  maxBuyingPriceSlider.setShowValue(true);
  maxBuyingPriceSlider.setShowLimits(true);
  maxBuyingPriceSlider.setLimits(43.55, 0.0, 200.0);
  maxBuyingPriceSlider.setNbrTicks(10);
  maxBuyingPriceSlider.setShowTicks(true);
  maxBuyingPriceSlider.setNumberFormat(G4P.DECIMAL, 2);
  maxBuyingPriceSlider.setOpaque(false);
  maxBuyingPriceSlider.addEventHandler(this, "maxBuyPriceSliderEvent");
}

// Variable declarations 
// autogenerated do not edit
GCustomSlider maxBuyingPriceSlider; 